name: create-backup

# Runs every day at 0:00 UTC time
on:
  # schedule:
    # - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo with our Dockerfile and stuff
      - uses: UCSDTESC/TESCEventsBackup@master
        # pass our AWS credentials through environment variables
        # also pass our other info (s3 bucket name, db name, etc.) through environment variables
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
